services:
  postgres:
    image: postgres:15-alpine
    container_name: cinema_db
    environment:
      POSTGRES_USER: cinema
      POSTGRES_PASSWORD: cinema123
      POSTGRES_DB: cinema
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
